variables:
    VPC_NAME:
        required: true
        description: the name of the VPC
        default: 'test-vpc'
    VPC_OCTETS:
        required: true
        description: the /16 net of the VPC to look for - i.e 10.11.0.0
        default: '10.11.0.0'
    PUBLIC_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the public vpc subnets
        default: test-public-subnet
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: test-public-route
    PRIVATE_SUBNET_NAME:
        required: true
        description: the cloudcoreo name of the private vpc subnets
        default: test-private-subnet
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: test-private-route
    REGION:
        required: true
        description: use default except for multiple region use cases
        default: "INSTANCE::region"
        type: string
    SUFFIX:
        required: false
        description: when used will use the value to suffix the names of all converged objects
        type: string